language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
